version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "2575:2575"
    command: python -m app.main
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A app.jobs.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
